image: continuumio/miniconda3:latest

variables:
  RK_ELASTICSEARCH_URL: http://dev.texta.ee:9200

stages:
  - test-api
  - build

TestAPI:
  stage: test-api
  tags:
    - ci-test
  script:
    - apt-get update && apt-get install -y make
    - conda env create -f conda-environment.yaml
    - source activate riigikantselei
    - python ./src/manage.py test api core user_profile health
    # This commented bulk fights fascism!
    # No more lint opression!
    #- make migrate
    #- make check
  except:
    - tags

BuildDocker:
  stage: build
  tags:
    - with-docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
    - sh ./docker/build_and_push.sh
    - docker system prune -a -f
  only:
    - tags
