image: continuumio/miniconda3:latest

variables:
  RK_ELASTICSEARCH_URL: http://ci-elastic:9200

services:
  - name: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    alias: ci-elastic
    command: [ "bin/elasticsearch", "-Ediscovery.type=single-node", "-Expack.security.enabled=false", "-Expack.security.enrollment.enabled=false"]

stages:
  - test-api

TestAPI:
  stage: test-api
  tags:
    - ci-test
  script:
    - apt-get update && apt-get install -y make
    - conda env create -f conda-environment.yaml
    - make migrate
    - make check
