image: continuumio/miniconda3:latest

variables:
  RK_ELASTICSEARCH_URL: http://elastic-dev.texta.ee:9200
  RK_CELERY_BROKER_URL: redis://redis:6379
  RK_CELERY_RESULT_BACKEND: redis://redis:6379

services:
  - name: redis:6
    alias: redis

stages:
  - test-api

TestAPI:
  stage: test-api
  tags:
    - ci-test
  script:
    - apt-get update && apt-get install -y make
    - conda env create -f conda-environment.yaml
    - make migrate
    # TODO: handle lack of redis and celery in CI env
    - make check
