name: riigikantselei
channels:
  - defaults
dependencies:
  # Put to 3.10 since 3.12 causes conflict errors with mysqlclient for some reason.
  - python=3.10
  - pip
  - mysqlclient
  - uwsgi
  - nginx
  - supervisor
  - pip:
      - requests
      - torch==2.3.1+cpu
      - -f https://download.pytorch.org/whl/torch_stable.html
      - FlagEmbedding
      - Django>5<6
      - djangorestframework
      - gunicorn
      - django-environ
      - django-cors-headers
      - celery[redis]<6
      - elasticsearch==8.*
      - elasticsearch_dsl==8.*
      - pytest
      - pre-commit
      - openai
      - numpy<2  # Breaking changes, some other packages did not take into account
      - tiktoken
      - fpdf2
      - matplotlib
