# Generated by Django 5.0.6 on 2024-06-13 14:13

import django.db.models.deletion
import rest_framework.authtoken.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'key',
                    models.CharField(
                        default=rest_framework.authtoken.models.Token.generate_key, max_length=50
                    ),
                ),
                (
                    'auth_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('is_manager', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_allowed_to_spend_resources', models.BooleanField(default=False)),
                ('custom_usage_limit_euros', models.FloatField(default=None, null=True)),
                (
                    'auth_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='user_profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
