# Generated by Django 5.0.7 on 2024-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='used_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
