# Generated by Django 5.1rc1 on 2024-07-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0002_userprofile_used_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
