# Generated by Django 5.1rc1 on 2024-07-29 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0003_userprofile_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='auth_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth_user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='user_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
