# Generated by Django 5.1rc1 on 2024-07-29 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0004_alter_passwordresettoken_auth_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='used_cost',
        ),
    ]
