# Generated by Django 5.1rc1 on 2024-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0005_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
