# Generated by Django 5.1rc1 on 2024-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0006_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
