# Generated by Django 5.0.7 on 2024-07-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_search', '0002_documentsearchqueryresult_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsearchconversation',
            name='max_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='documentsearchconversation',
            name='min_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
