# Generated by Django 5.1rc1 on 2024-07-29 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document_search', '0004_documentsearchqueryresult_is_context_pruned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsearchconversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aggregationtask',
            name='result',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='celery_task',
                to='document_search.documentaggregationresult',
            ),
        ),
        migrations.AlterField(
            model_name='documentaggregationresult',
            name='conversation',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='aggregation_result',
                to='document_search.documentsearchconversation',
            ),
        ),
        migrations.AlterField(
            model_name='documentsearchconversation',
            name='auth_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='documentsearchqueryresult',
            name='conversation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='query_results',
                to='document_search.documentsearchconversation',
            ),
        ),
        migrations.AlterField(
            model_name='documenttask',
            name='result',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='celery_task',
                to='document_search.documentsearchqueryresult',
            ),
        ),
    ]
