# Generated by Django 5.0.7 on 2024-07-12 13:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSearchConversation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('system_input', models.TextField()),
                ('indices', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('min_year', models.IntegerField(default=None, null=True)),
                ('max_year', models.IntegerField(default=None, null=True)),
                (
                    'auth_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextSearchQueryResult',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('model', models.CharField(default=None, max_length=100, null=True)),
                ('user_input', models.TextField(default=None, null=True)),
                ('response', models.TextField(default=None, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=None, null=True)),
                ('output_tokens', models.PositiveIntegerField(default=None, null=True)),
                ('total_cost', models.FloatField(default=None, null=True)),
                ('response_headers', models.JSONField(default=None, null=True)),
                ('references', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='query_results',
                        to='text_search.textsearchconversation',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'PENDING'),
                            ('STARTED', 'STARTED'),
                            ('SUCCESS', 'SUCCESS'),
                            ('FAILURE', 'FAILURE'),
                        ],
                        default='PENDING',
                        max_length=50,
                    ),
                ),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                (
                    'result',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='celery_task',
                        to='text_search.textsearchqueryresult',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
