# Generated by Django 5.1b1 on 2024-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('text_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsearchconversation',
            name='indices',
        ),
        migrations.AddField(
            model_name='textsearchconversation',
            name='dataset_names_string',
            field=models.TextField(default=None, null=True),
        ),
    ]
