# Generated by Django 5.0.7 on 2024-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('text_search', '0002_remove_textsearchconversation_indices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsearchqueryresult',
            name='is_context_pruned',
            field=models.BooleanField(default=False),
        ),
    ]
