# Generated by Django 5.1rc1 on 2024-08-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('text_search', '0004_alter_textsearchconversation_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='textsearchconversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textsearchconversation',
            name='auth_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='conversation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='query_results',
                to='text_search.textsearchconversation',
            ),
        ),
        migrations.AlterField(
            model_name='texttask',
            name='result',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='celery_task',
                to='text_search.textsearchqueryresult',
            ),
        ),
    ]
