# Generated by Django 5.0.6 on 2024-07-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_textsearchconversation_textsearchqueryresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsearchqueryresult',
            name='celery_task_id',
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='document_types_string',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='input_tokens',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='max_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='min_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='model',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='output_tokens',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='response',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='response_headers',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='total_cost',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textsearchqueryresult',
            name='user_input',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'PENDING'),
                            ('STARTED', 'STARTED'),
                            ('SUCCESS', 'SUCCESS'),
                            ('FAILURE', 'FAILURE'),
                        ],
                        default='PENDING',
                        max_length=50,
                    ),
                ),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                (
                    'result',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='celery_task',
                        to='core.textsearchqueryresult',
                    ),
                ),
            ],
        ),
    ]
