# Generated by Django 5.0.6 on 2024-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_remove_textsearchqueryresult_celery_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsearchqueryresult',
            name='document_types_string',
        ),
        migrations.RemoveField(
            model_name='textsearchqueryresult',
            name='max_year',
        ),
        migrations.RemoveField(
            model_name='textsearchqueryresult',
            name='min_year',
        ),
        migrations.AddField(
            model_name='textsearchconversation',
            name='document_types_string',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='textsearchconversation',
            name='max_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='textsearchconversation',
            name='min_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
