# Generated by Django 5.0.6 on 2024-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_remove_textsearchqueryresult_document_types_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsearchqueryresult',
            name='references',
            field=models.JSONField(default=None, null=True),
        ),
    ]
