# Generated by Django 5.0.7 on 2024-07-11 11:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_textsearchqueryresult_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsearchqueryresult',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
