# Generated by Django 5.0.7 on 2024-07-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_textsearchqueryresult_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsearchconversation',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='textsearchqueryresult',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TextSearchConversation',
        ),
        migrations.DeleteModel(
            name='TextSearchQueryResult',
        ),
    ]
